### PR TITLE
Improve lambda case

### PR DESCRIPTION
**Pull request by Futarimiti**
Correctly indent further cases for a lambda case expression where the first pattern is on the same line as `\case`.

Examples:

```haskell
lambda_case :: Maybe Int -> Int
lambda_case = \case Nothing -> 0
>>>>>>>>>>>>>>>>>>>>Just n -> n

lambda_case2 :: (Bool, Bool) -> Int
lambda_case2 = \case(True,True)->1
>>>>>>>>>>>>>>>>>>>>(_, False) -> 3
```

### CODE REVIEW

**Comment by Futarimiti** [comment]
Let me know if you want me to add tests as well

**Comment by itchyny** [comment]
Yes, please add tests.

**Comment by Futarimiti** [comment]
Just found out `\ case` would be valid lambda case as well, which is not covered here

**Comment by Futarimiti** [comment]
Good enough I believe. Take a look! @itchyny

**Review by itchyny — APPROVED** [review]
Thank you!

**Pull request merged**
